# Generated by Django 2.0.4 on 2018-04-18 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180414_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.User'),
        ),
        migrations.AlterField(
            model_name='commentnews',
            name='id_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Comment'),
        ),
        migrations.AlterField(
            model_name='commentnews',
            name='id_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.News'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='id_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.News'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.User'),
        ),
        migrations.AlterField(
            model_name='interested',
            name='id_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.News'),
        ),
        migrations.AlterField(
            model_name='interested',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.User'),
        ),
    ]
