# Generated by Django 2.0.4 on 2018-05-20 01:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180419_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentnews',
            options={'verbose_name_plural': 'CommentNews'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.IntegerField(choices=[(1, 'BANNED'), (2, 'GUEST'), (3, 'USER'), (4, 'MODERATOR'), (5, 'ADMINISTRATOR'), (6, 'HEAD_ADMINISTRATOR')]),
        ),
    ]
