# Generated by Django 2.0.4 on 2018-06-06 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180520_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentnews',
            name='id_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Comment'),
        ),
        migrations.AlterField(
            model_name='commentnews',
            name='id_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.News'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='id_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.News'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User'),
        ),
        migrations.AlterField(
            model_name='interested',
            name='id_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.News'),
        ),
        migrations.AlterField(
            model_name='interested',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User'),
        ),
    ]
